trigger:
  branches:
    include:
      - main

  paths:
    exclude:
      - README.md

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 0

  - bash: az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)' --use-git-aliases true
    displayName: "Set default Azure DevOps organization and project"

  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: Install Node.js

  - script: |
      npm install -g semver-compare-cli
    displayName: Install semver-compare-cli

  - task: AzurePowerShell@5
    displayName: Get Changed Modules
    inputs:
      azureSubscription: aad-app-adr-pf-svcp # Update with your SPN name
      ScriptType: FilePath
      ScriptPath: ./scripts/azure-devops/get-changed-modules.ps1
      ScriptArguments: -NewRevision $(Build.SourceVersion)
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: Create Tag
    inputs:
      azureSubscription: aad-app-adr-pf-svcp # Update with your SPN name
      ScriptType: FilePath
      ScriptPath: ./scripts/azure-devops/create-tag.ps1
      ScriptArguments: -NewRevision $(Build.SourceVersion)
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: Publish Module
    inputs:
      azureSubscription: aad-app-adr-pf-svcp # Update with your SPN name
      ScriptType: FilePath
      ScriptPath: ./scripts/azure-devops/publish-module.ps1
      ScriptArguments: -RegistryServer <insert-acr-uri>.azurecr.io # Update with your acr name
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: Refresh Module Table
    inputs:
      azureSubscription: aad-app-adr-pf-svcp # Update with your SPN name
      ScriptType: FilePath
      ScriptPath: ./scripts/azure-devops/refresh-module-table.ps1
      ScriptArguments: -ExecutionPolicy Unrestricted
      azurePowerShellVersion: LatestVersion
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)