name: On pull request

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        run: |
          LC_ALL=C
          local_branch=$GITHUB_HEAD_REF
          valid_branch_regex="^(feature|bugfix)\/[a-z0-9-]+$"
          message="INVALID! branch name. Branch names in this repo must adhere to this regex convention: $valid_branch_regex. Branching conventions can be found here: https://github.com/arincoau/arinco-bicep-modules/blob/main/CONTRIBUTING.md. Your commit will be rejected. You should rename your branch to a valid name and try again."
          if [[ ! $local_branch =~ $valid_branch_regex ]]
          then
              echo "$message"
              exit 1
          else
            echo "Branch name valid"
          fi

  get-module-to-validate:
    uses: ./.github/workflows/get-changed-module.yml

  validate-module-files:
    runs-on: ubuntu-latest
    needs: get-module-to-validate
    if: needs.get-module-to-validate.outputs.module_dir
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Adding a step to explicitly install the latest Bicep CLI because there is
      # always a delay in updating Bicep CLI in the job runner environments.
      - name: Install the latest Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --version

      - name: Install Bicep registry module tool
        run: dotnet tool install --global Azure.Bicep.RegistryModuleTool

      - name: Validate module files
        run: brm validate
        working-directory: ${{ needs.get-module-to-validate.outputs.module_dir }}

  validate-non-module-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run prettier:check
