name: On push main

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: write

jobs:
  get-module-to-publish:
    uses: ./.github/workflows/get-changed-module.yml

  create-tag:
    runs-on: ubuntu-latest
    needs: get-module-to-publish
    if: ${{ needs.get-module-to-publish.outputs.module_dir }}
    outputs:
      tag: ${{ steps.create-tag.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install semver
        run: npm install semver

      - name: Get base and head versions
        id: get-versions
        env:
          PublicRelease: true
        run: |
          echo "base_version=$(nbgv get-version ${{ github.event.before }} --format json | jq '.SemVer2')" >> $GITHUB_OUTPUT
          echo "head_version=$(nbgv get-version ${{ github.event.after }} --format json | jq '.SemVer2')" >> $GITHUB_OUTPUT
        working-directory: ${{ needs.get-module-to-publish.outputs.module_dir }}

      - name: Create tag
        id: create-tag
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const script = require("./scripts/github-actions/create-tag.js")
            return await script({
              require,
              github,
              context,
              core,
              moduleDir: "${{ needs.get-module-to-publish.outputs.module_dir }}",
              baseVersion: ${{ steps.get-versions.outputs.base_version }},
              headVersion: ${{ steps.get-versions.outputs.head_version }},
            })

  publish-module:
    needs: create-tag
    if: needs.create-tag.outputs.tag
    uses: ./.github/workflows/publish-module.yml
    with:
      tag: ${{ needs.create-tag.outputs.tag }}
    secrets:
      PUBLISH_CLIENT_ID: ${{ secrets.PUBLISH_CLIENT_ID }}
      PUBLISH_TENANT_ID: ${{ secrets.PUBLISH_TENANT_ID }}
      PUBLISH_SUBSCRIPTION_ID: ${{ secrets.PUBLISH_SUBSCRIPTION_ID }}
      PUBLISH_REGISTRY_SERVER: ${{ secrets.PUBLISH_REGISTRY_SERVER }}

  refresh-module-table:
    needs: create-tag
    if: needs.create-tag.outputs.tag
    uses: ./.github/workflows/refresh-module-table.yml
    # secrets: # this is only required when using a GH App to create pull requests instead of the default GITHUB_TOKEN
    #   APP_ID: ${{ secrets.APP_ID }}
    #   APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
