name: "Pull Request Management"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: "This PR is stale because it has been open 30 days with no activity. Comment on this pull request or this will be closed in 10 days."
          close-pr-message: "This PR was closed because it has been stalled for 10 days with no activity."
          days-before-pr-stale: 30
          days-before-pr-close: 10
          days-before-issue-stale: -1
          days-before-issue-close: -1
